'use strict';

goog.provide('Blockly.Msg.actuators.en');

goog.require('Blockly.Msg');

MSG.catSensorkit = "传感器套件";

Blockly.Msg.SENSORKIT_PIN_NUMBER_TITLE = "GPIO";
Blockly.Msg.SENSORKIT_PIN_NUMBER_TOOLTIP = "GPIO 引脚编号";

Blockly.Msg.SENSORKIT_PIN_STATUS_TOOLTIP = "GPIO 引脚状态";

Blockly.Msg.SENSORKIT_PIN_IRQ_TRIGGER = "中断触发";
Blockly.Msg.SENSORKIT_PIN_IRQ_TRIGGER_TOOLTIP = "中断触发";

Blockly.Msg.SENSORKIT_PIN_COLOUR_TOOLTIP = "颜色";

Blockly.Msg.SENSORKIT_PIN_SWITCH_TOOLTIP = "开或关";


Blockly.Msg.SENSORKIT_PIN_DOUBLE_LED_TOOLTIP = "双色LED";



Blockly.Msg.SENSORKIT_LED_SET_VALUE_TITLE1 = "设置LED";
Blockly.Msg.SENSORKIT_LED_SET_VALUE_TITLE2 = "为";
Blockly.Msg.SENSORKIT_LED_SET_VALUE_TOOLTIP = "设置LED为开或关.";

Blockly.Msg.SENSORKIT_LED_ON_TITLE1 = "设置LED";
Blockly.Msg.SENSORKIT_LED_ON_TITLE2 = "开";
Blockly.Msg.SENSORKIT_LED_ON_TOOLTIP = "设置LED为开";

Blockly.Msg.SENSORKIT_LED_OFF_TITLE1 = "设置LED";
Blockly.Msg.SENSORKIT_LED_OFF_TITLE2 = "关";
Blockly.Msg.SENSORKIT_LED_OFF_TOOLTIP = "设置LED为关";

Blockly.Msg.SENSORKIT_RGB_SET_VALUE_TITLE1 = "设置RGB中R连接";
Blockly.Msg.SENSORKIT_RGB_SET_VALUE_TITLE2 = "              G连接";
Blockly.Msg.SENSORKIT_RGB_SET_VALUE_TITLE3 = "              B连接";
Blockly.Msg.SENSORKIT_RGB_SET_VALUE_TITLE4 = "     选取颜色为";
Blockly.Msg.SENSORKIT_RGB_SET_VALUE_TOOLTIP = "设置RGB颜色";

Blockly.Msg.SENSORKIT_BUZZER_SET_VALUE_TITLE1 = "设置有源蜂鸣器";
Blockly.Msg.SENSORKIT_BUZZER_SET_VALUE_TITLE2 = "为";
Blockly.Msg.SENSORKIT_BUZZER_SET_VALUE_TOOLTIP = "设置有源蜂鸣器为开或关.";

Blockly.Msg.SENSORKIT_BUZZER_ACTIVE_TITLE1 = "设置有源蜂鸣器";
Blockly.Msg.SENSORKIT_BUZZER_ACTIVE_TITLE2 = "为开";
Blockly.Msg.SENSORKIT_BUZZER_ACTIVE_TOOLTIP = "设置有源蜂鸣器为开.";

Blockly.Msg.SENSORKIT_BUZZER_PASSIVE_TITLE1 = "设置有源蜂鸣器";
Blockly.Msg.SENSORKIT_BUZZER_PASSIVE_TITLE2 = "为关";
Blockly.Msg.SENSORKIT_BUZZER_PASSIVE_TOOLTIP = "设置有源蜂鸣器为关.";

Blockly.Msg.SENSORKIT_DOUBLELED_SET_VALUE_TITLE1 = "设置双色LED中R连接";
Blockly.Msg.SENSORKIT_DOUBLELED_SET_VALUE_TITLE2 = "                      G连接";
Blockly.Msg.SENSORKIT_DOUBLELED_SET_VALUE_TITLE3 = "               选取颜色为";
Blockly.Msg.SENSORKIT_DOUBLELED_SET_VALUE_TOOLTIP = "设置双色LED颜色";

Blockly.Msg.SENSORKIT_AUTOFLASH_SET_VALUE_TITLE1 = "设置自动闪烁LED";
Blockly.Msg.SENSORKIT_AUTOFLASH_SET_VALUE_TITLE2 = "为";
Blockly.Msg.SENSORKIT_AUTOFLASH_SET_VALUE_TOOLTIP = "设置自动闪烁LED为开或关.";

Blockly.Msg.SENSORKIT_RELAY_SET_VALUE_TITLE1 = "设置继电器";
Blockly.Msg.SENSORKIT_RELAY_SET_VALUE_TITLE2 = "为";
Blockly.Msg.SENSORKIT_RELAY_SET_VALUE_TOOLTIP = "设置继电器为开或关.";

Blockly.Msg.SENSORKIT_LASER_SET_VALUE_TITLE1 = "设置激光发射器";
Blockly.Msg.SENSORKIT_LASER_SET_VALUE_TITLE2 = "为";
Blockly.Msg.SENSORKIT_LASER_SET_VALUE_TOOLTIP = "设置激光发射器为.";


Blockly.Msg.SENSORKIT_PIN_NUMBER_TITLE = "GPIO"
Blockly.Msg.SENSORKIT_PIN_NUMBER_TOOLTIP = "GPIO引脚编号";

Blockly.Msg.SENSORKIT_PIN_STATUS_TOOLTIP = "GPIO引脚状态";

Blockly.Msg.SENSORKIT_PIN_IRQ_TRIGGER = "中断触发";
Blockly.Msg.SENSORKIT_PIN_IRQ_TRIGGER_TOOLTIP = "中断触发";


Blockly.Msg.SENSORKIT_BUTTON_GET_VALUE_TITLE1 = "获取按钮";
Blockly.Msg.SENSORKIT_BUTTON_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_BUTTON_GET_VALUE_TOOLTIP = "获取按钮的值.";

Blockly.Msg.SENSORKIT_POTENTIOMETER_GET_VALUE_TITLE1 = "获取电位计";
Blockly.Msg.SENSORKIT_POTENTIOMETER_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_POTENTIOMETER_GET_VALUE_TOOLTIP = "获取电位计的值";

Blockly.Msg.SENSORKIT_SOUND_GET_VALUE_TITLE1 = "获取声音";
Blockly.Msg.SENSORKIT_SOUND_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_SOUND_GET_VALUE_TOOLTIP = "获取声音的值.";

Blockly.Msg.SENSORKIT_ULTRASONIC_GET_VALUE_TITLE1 = "获取超声波测距";
Blockly.Msg.SENSORKIT_ULTRASONIC_GET_VALUE_TITLE3 = "";
Blockly.Msg.SENSORKIT_ULTRASONIC_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_ULTRASONIC_VALUE_TOOLTIP = "获取超声波测距的值.";

Blockly.Msg.SENSORKIT_TILTSWITCH_GET_VALUE_TITLE1 = "获取倾斜开关";
Blockly.Msg.SENSORKIT_TILTSWITCH_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_TILTSWITCH_GET_VALUE_TOOLTIP = "获取倾斜开关的值.";

Blockly.Msg.SENSORKIT_REEDSWITCH_GET_VALUE_TITLE1 = "获取磁簧开关";
Blockly.Msg.SENSORKIT_REEDSWITCH_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_REEDSWITCH_GET_VALUE_TOOLTIP = "获取磁簧开关的值.";


Blockly.Msg.SENSORKIT_PHOTOINTERRUPTER_GET_VALUE_TITLE1 = "获取光电断路器";
Blockly.Msg.SENSORKIT_PHOTOINTERRUPTER_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_PHOTOINTERRUPTER_GET_VALUE_TOOLTIP = "获取光电断路器的值.";

Blockly.Msg.SENSORKIT_RAINDETECTION_GET_VALUE_TITLE1 = "获取雨水检测";
Blockly.Msg.SENSORKIT_RAINDETECTION_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_RAINDETECTION_GET_VALUE_TOOLTIP = "获取雨水检测的值.";

Blockly.Msg.SENSORKIT_TEMPERATURE_GET_VALUE_TITLE1 = "获取温度";
Blockly.Msg.SENSORKIT_TEMPERATURE_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_TEMPERATURE_GET_VALUE_TOOLTIP = "获取温度的值.";

Blockly.Msg.SENSORKIT_IROBSTACLE_GET_VALUE_TITLE1 = "获取避障";
Blockly.Msg.SENSORKIT_IROBSTACLE_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_IROBSTACLE_GET_VALUE_TOOLTIP = "获取避障的值.";

Blockly.Msg.SENSORKIT_PHOTORESISTOR_GET_VALUE_TITLE1 = "获取光敏电阻";
Blockly.Msg.SENSORKIT_PHOTORESISTOR_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_PHOTORESISTOR_GET_VALUE_TOOLTIP = "获取光敏电阻的值.";

Blockly.Msg.SENSORKIT_FLAME_GET_VALUE_TITLE1 = "获取火焰传感器";
Blockly.Msg.SENSORKIT_FLAME_GET_VALUE_TITLE3 = "";
Blockly.Msg.SENSORKIT_FLAME_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_FLAME_VALUE_TOOLTIP = "获取火焰传感器的值.";

Blockly.Msg.SENSORKIT_GASSENSOR_GET_VALUE_TITLE1 = "获取气体传感器";
Blockly.Msg.SENSORKIT_GASSENSOR_GET_VALUE_TITLE3 = "";
Blockly.Msg.SENSORKIT_GASSENSOR_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_GASSENSOR_VALUE_TOOLTIP = "获取火焰传感器的值.";

Blockly.Msg.SENSORKIT_TOUCHSWITCH_GET_VALUE_TITLE1 = "获取触摸开关";
Blockly.Msg.SENSORKIT_TOUCHSWITCH_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_TOUCHSWITCH_GET_VALUE_TOOLTIP = "获取触摸开关的值.";

Blockly.Msg.SENSORKIT_DS18B20_GET_VALUE_TITLE1 = "获取ds18b20";
Blockly.Msg.SENSORKIT_DS18B20_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_DS18B20_GET_VALUE_TOOLTIP = "获取ds18b20温度传感器的值.";

Blockly.Msg.SENSORKIT_ROTARY_ENCODER_GET_VALUE_TITLE1 = "获取旋转编码器";
Blockly.Msg.SENSORKIT_ROTARY_ENCODER_GET_VALUE_TITLE2 = "                     的值";
Blockly.Msg.SENSORKIT_ROTARY_ENCODER_GET_VALUE_TITLE3 = "";
Blockly.Msg.SENSORKIT_ROTARY_ENCODER_VALUE_TOOLTIP = "获取旋转编码器的值.";

Blockly.Msg.SENSORKIT_TRACKING_GET_VALUE_TITLE1 = "获取跟踪传感器";
Blockly.Msg.SENSORKIT_TRACKING_GET_VALUE_TITLE2 = "的值";
Blockly.Msg.SENSORKIT_TRACKING_GET_VALUE_TOOLTIP = "获取跟踪传感器的值.";


Blockly.Msg.SENSORKIT_ANALOGHALLSWITCH_GET_VALUE_TITLE1 = "模拟霍尔传感器 DO";
Blockly.Msg.SENSORKIT_ANALOGHALLSWITCH_GET_VALUE_TITLE2 = "获取";
Blockly.Msg.SENSORKIT_ANALOGHALLSWITCH_GET_VALUE_TITLE3 = "的值 AO";
Blockly.Msg.SENSORKIT_ANALOGHALLSWITCH_VALUE_TOOLTIP = " 获取模拟霍尔传感器的值.";
